name: 'genetic_algorithm'
version: #your app version here.
description: #description of your app here.
environment:
 sdk: '>=1.0.0 <2.0.0'

#Dependencies for your app:
dev_dependencies:
 browser: '>=0.10.0 <0.11.0'
 over_react: '^1.2.0'
 w_flux: '2.6.0'
 dart_to_js_script_rewriter: '^1.0.1'

#Transformers your app may need:
transformers:
- over_react
- dart_to_js_script_rewriter
